use super::cost::slope_grid;
use super::cost::step_cost;
use super::dijkstra::{dijkstra_cost_field, reconstruct_path};
use super::TraverseParams;

#[test]
fn dijkstra_finds_min_cost_crossing_on_tiny_grid() {
    // 3x3 uniform-cost grid (slope below budget, no channel, h=0 -> step_cost = cell_m everywhere).
    // Source = all of column 0; target = column 2. Shortest path is a straight horizontal line, 3 cells.
    let n = 3;
    let slope = vec![0.0_f64; n * n];
    let h = vec![0.0_f64; n * n];
    let chan = vec![0.0_f64; n * n];
    let p = TraverseParams {
        slope_budget: 0.28,
        slope_penalty: 0.0,
        drainage_bias: 0.0,
        ..Default::default()
    };
    let cell = 100.0;
    let sources: Vec<(usize, usize)> = (0..n).map(|r| (r, 0)).collect();
    let (prev, _dist, target) =
        dijkstra_cost_field(&slope, &h, &chan, n, n, cell, &p, &sources, |_r, c| c == n - 1);
    assert!(target >= 0, "no target reached");
    let path = reconstruct_path(&prev, target as usize, n);
    assert_eq!(path.first().unwrap().1, 0, "path must start at column 0");
    assert_eq!(path.last().unwrap().1, n - 1, "path must end at column n-1");
    assert_eq!(path.len(), n, "straight crossing is n cells");
}

#[test]
fn dijkstra_tiebreak_prefers_lowest_flattened_index() {
    // Uniform-cost grid: every cell costs the same, so EVERY source/path is cost-tied.
    // The (cost, idx) min-heap must resolve those ~ties by lowest flattened index, exactly
    // like Python heapq on (cost, idx) tuples. With all of column 0 as sources, row 0 (idx 0)
    // is the smallest flattened index, so the popped target on row 0 must be reached via the
    // row-0 source, giving a straight path along row 0: [(0,0),(0,1),(0,2)].
    let n = 3;
    let slope = vec![0.0_f64; n * n];
    let h = vec![0.0_f64; n * n];
    let chan = vec![0.0_f64; n * n];
    let p = TraverseParams {
        slope_budget: 0.28,
        slope_penalty: 0.0,
        drainage_bias: 0.0,
        ..Default::default()
    };
    let cell = 100.0;
    let sources: Vec<(usize, usize)> = (0..n).map(|r| (r, 0)).collect();
    let (prev, _dist, target) =
        dijkstra_cost_field(&slope, &h, &chan, n, n, cell, &p, &sources, |_r, c| c == n - 1);
    assert!(target >= 0, "no target reached");
    // Lowest-index target column-2 cell is (0,2) = idx 2; lower-index wins the tie.
    assert_eq!(target, 2, "tie-break must pop the lowest flattened-index target first");
    let path = reconstruct_path(&prev, target as usize, n);
    assert_eq!(
        path,
        vec![(0, 0), (0, 1), (0, 2)],
        "lower-index tie-break yields the straight row-0 path"
    );
}

#[test]
fn step_cost_matches_python_formula() {
    let p = TraverseParams {
        slope_budget: 0.28,
        slope_penalty: 2.0,
        drainage_bias: 0.5,
        ..Default::default()
    };
    let cell = 100.0;
    // slope below budget, chan 0, h>0 -> over=0, reward=0 -> base=cell=100
    assert!((step_cost(0.1, 1.0, 0.0, cell, &p) - 100.0).abs() < 1e-9);
    // slope over budget by 0.22 -> base=100*(1+2*0.22)=144; reward 0 -> 144
    assert!((step_cost(0.5, 1.0, 0.0, cell, &p) - 144.0).abs() < 1e-9);
    // chan=1,h=0 -> reward=0.5*(0.6*1+0.4*0)=0.3; base=100 -> 70
    assert!((step_cost(0.1, 0.0, 1.0, cell, &p) - 70.0).abs() < 1e-9);
    // floor: huge reward can't go below cell*0.05=5
    let p2 = TraverseParams { drainage_bias: 100.0, ..p };
    assert!((step_cost(0.1, -1.0, 1.0, cell, &p2) - 5.0).abs() < 1e-9);
}

#[test]
fn slope_grid_matches_known_ramp() {
    // A linear ramp in x: height[r][c] = c (so y = c*height_scale). With cell_m and height_scale,
    // dx everywhere = height_scale/cell_m (constant), dz = 0 -> slope = height_scale/cell_m everywhere.
    let n = 5usize;
    let scene_width_m = 400.0; // cell_m = 400/4 = 100
    let height_scale_m = 260.0;
    let mut h = vec![0.0_f64; n * n];
    for r in 0..n {
        for c in 0..n {
            h[r * n + c] = c as f64;
        }
    }
    let s = slope_grid(&h, n, scene_width_m, height_scale_m);
    let expected = height_scale_m / 100.0; // 2.6
    for v in &s {
        assert!((v - expected).abs() < 1e-9, "got {v} expected {expected}");
    }
}

#[test]
fn slope_grid_matches_numpy_nonlinear_reference() {
    // Hard parity check against real numpy np.gradient(edge_order=1) on a NON-linear field
    // (so interior central differences vs one-sided edges actually diverge — the linear ramp
    // tests above cannot distinguish them). `expected` was generated by feeding this exact `h`
    // through numpy: y = h*height_scale; dz,dx = np.gradient(y, cell_m, cell_m, edge_order=1);
    // slope = sqrt(dx*dx + dz*dz), with cell_m = scene_width_m/(n-1).
    let n = 6usize;
    let scene_width_m = 1234.5_f64;
    let height_scale_m = 260.0_f64;
    let h: [f64; 36] = [
        -1.4238250364546312, 1.2637284581291104, -0.8706617379590857, -0.2591732349343976,
        -0.07534330701052097, -0.740884652085609, -1.3677927017829434, 0.6488928021930399,
        0.361058113054895, -1.95286306301219, 2.347409654378852, 0.9684969057519236,
        -0.7593871804245066, 0.9021982742122517, -0.46695317332055025, -0.06068951873702798,
        0.7888443445192008, -1.2566681331396765, 0.5758575143959287, 1.3989789947237192,
        1.3222980607327857, -0.29969851529910546, 0.9029193414250598, -1.6215827341822058,
        -0.15818926067687128, 0.44948393210667503, -1.343601072486395, -0.08168759069683368,
        1.7247399323163304, 2.61815942636784, 0.777361343810768, 0.8286331955673406,
        -0.9589883130180109, -1.2093882869743162, -1.4122920134741184, 0.5415468299050529,
    ];
    let expected: [f64; 36] = [
        2.830764516736808, 0.7099518525743221, 1.524914108779285, 1.832053888329938,
        2.563875635575847, 1.9317028177601288, 2.152309690315736, 0.9299803060274752,
        1.3862932745835663, 1.0510800279793375, 1.604070656571484, 1.477252422481672,
        2.027050403542578, 0.42389569058804816, 0.7163764900271036, 1.0931000429180115,
        0.9874232039002444, 2.5494550536561817, 0.9227868522083533, 0.4596582025318273,
        1.0064855254901726, 0.22109165366811037, 0.8527946306295267, 3.3510882359034344,
        0.6486509033766904, 0.692639888871268, 1.2332934358211387, 1.6850779314901092,
        1.8726509693836726, 1.477279540965105, 0.9866673559179334, 0.9976197956016356,
        1.1469680730902345, 1.211282094650801, 3.429706801530175, 3.0025645438282016,
    ];
    let s = slope_grid(&h, n, scene_width_m, height_scale_m);
    for (i, (&got, &exp)) in s.iter().zip(expected.iter()).enumerate() {
        assert!((got - exp).abs() < 1e-12, "idx {i}: got {got} expected {exp}");
    }
}

#[test]
fn slope_grid_diagonal_ramp_uses_hypot() {
    // 2D ramp: height[r][c] = r + c. Both dz and dx == height_scale/cell_m everywhere
    // (central interior AND one-sided edges, since the field is linear). slope == that * sqrt(2).
    let n = 5usize;
    let scene_width_m = 400.0; // cell_m = 100
    let height_scale_m = 260.0;
    let mut h = vec![0.0_f64; n * n];
    for r in 0..n {
        for c in 0..n {
            h[r * n + c] = (r + c) as f64;
        }
    }
    let s = slope_grid(&h, n, scene_width_m, height_scale_m);
    let g = height_scale_m / 100.0; // per-axis gradient 2.6
    let expected = (2.0_f64).sqrt() * g;
    for v in &s {
        assert!((v - expected).abs() < 1e-9, "got {v} expected {expected}");
    }
}
