//! Parity tests: `array_ops.rs` (Rust) vs the Python oracle.
//!
//! Loads the committed fixture `tools/dem_pack/fixtures/array_ops_fixtures.json`
//! (generated by `tools/dem_pack/export_array_ops_fixtures.py`) and asserts every
//! Rust output reproduces the Python `expected` field within a tight epsilon.
//!
//! * gaussian_filter_nearest: separable Gaussian convolution with scipy's exact kernel
//!   + symmetric accumulation order => matches scipy to ~1e-15 (single-ULP region).
//! * flow_accumulation_mfd: bit-exact on tie-free noise inputs; on inputs with exactly
//!   equal heights the stable-vs-numpy tie ordering perturbs the result by at most
//!   one-ULP f64 accumulation noise (~1e-15), well under the asserted ceiling.

use crate::array_ops as ops;
use serde::Deserialize;

// Documented ceiling. The real max delta is ~1e-15 (printed below); 1e-9 is a generous
// headroom that still catches any algorithmic divergence (which would be >> 1e-9).
const EPS: f64 = 1e-9;

const FIXTURE: &str = include_str!("../../../tools/dem_pack/fixtures/array_ops_fixtures.json");

#[derive(Deserialize)]
struct Doc {
    generator_version: String,
    records: Vec<Record>,
}

#[derive(Deserialize)]
struct Record {
    op: String,
    inputs: serde_json::Value,
    rows: usize,
    cols: usize,
    field: Vec<f64>,
    expected: Vec<f64>,
}

fn f(v: &serde_json::Value, key: &str) -> f64 {
    v.get(key)
        .and_then(|x| x.as_f64())
        .unwrap_or_else(|| panic!("missing/invalid f64 field {key} in {v}"))
}

#[test]
fn array_ops_matches_python_oracle() {
    let doc: Doc = serde_json::from_str(FIXTURE).expect("parse array_ops_fixtures.json");
    assert_eq!(doc.generator_version, "array_ops_fixtures/v1");
    assert!(!doc.records.is_empty(), "fixture has no records");

    let mut max_gauss = 0.0_f64;
    let mut worst_gauss = String::new();
    let mut max_flow = 0.0_f64;
    let mut worst_flow = String::new();
    let mut n_gauss = 0usize;
    let mut n_flow = 0usize;

    for r in &doc.records {
        assert_eq!(
            r.field.len(),
            r.rows * r.cols,
            "fixture field len mismatch for {}",
            r.inputs
        );
        assert_eq!(
            r.expected.len(),
            r.rows * r.cols,
            "fixture expected len mismatch for {}",
            r.inputs
        );

        match r.op.as_str() {
            "gaussian_filter_nearest" => {
                let got = ops::gaussian_filter_nearest(
                    &r.field,
                    r.rows,
                    r.cols,
                    f(&r.inputs, "sigma"),
                    f(&r.inputs, "truncate"),
                );
                track(&mut max_gauss, &mut worst_gauss, &r.inputs, &got, &r.expected);
                n_gauss += 1;
            }
            "flow_accumulation_mfd" => {
                let got = ops::flow_accumulation_mfd(
                    &r.field,
                    r.rows,
                    r.cols,
                    f(&r.inputs, "power"),
                );
                track(&mut max_flow, &mut worst_flow, &r.inputs, &got, &r.expected);
                n_flow += 1;
            }
            other => panic!("fixture has unknown op {other:?}"),
        }
    }

    eprintln!(
        "[array_ops parity] gaussian: {n_gauss} records, max |delta| = {max_gauss:.3e} \
         (worst: {worst_gauss})"
    );
    eprintln!(
        "[array_ops parity] flow_acc: {n_flow} records, max |delta| = {max_flow:.3e} \
         (worst: {worst_flow})"
    );

    assert!(
        max_gauss < EPS,
        "gaussian_filter_nearest parity exceeded EPS={EPS:.1e}: max |delta|={max_gauss:.3e} at {worst_gauss}"
    );
    assert!(
        max_flow < EPS,
        "flow_accumulation_mfd parity exceeded EPS={EPS:.1e}: max |delta|={max_flow:.3e} at {worst_flow}"
    );
}

fn track(
    max: &mut f64,
    worst: &mut String,
    inputs: &serde_json::Value,
    got: &[f64],
    want: &[f64],
) {
    let mut local_max = 0.0_f64;
    let mut at = 0usize;
    for (i, (&g, &w)) in got.iter().zip(want.iter()).enumerate() {
        let d = (g - w).abs();
        if d > local_max {
            local_max = d;
            at = i;
        }
    }
    if local_max > *max {
        *max = local_max;
        *worst = format!(
            "inputs={inputs} cell={at} got={:.17} want={:.17}",
            got[at], want[at]
        );
    }
}
