//! Whole-array WorldGen10 operators ported bit-closely from the Python oracle.
//!
//! These are the two NON-per-point operators that every biome recipe needs, ported
//! from their Python originals and proven by committed fixtures
//! (`tools/dem_pack/fixtures/array_ops_fixtures.json`, generated by
//! `tools/dem_pack/export_array_ops_fixtures.py`):
//!
//! * [`gaussian_filter_nearest`] reproduces
//!   `scipy.ndimage.gaussian_filter(field, sigma, mode='nearest', truncate)` — exactly
//!   what `tools/dem_pack/seam_safe.py::apron_blur_crop` runs internally.
//! * [`flow_accumulation_mfd`] reproduces
//!   `tools/dem_pack/geography_skeleton.py::_flow_accumulation_mfd(surface, power)`.
//!
//! All fields are flat row-major (`C` order) `f64` slices of length `rows * cols`.

/// Gaussian blur of a 2-D field with scipy's `mode='nearest'` (clamp-to-edge) boundary.
///
/// Bit-close port of `scipy.ndimage.gaussian_filter(field, sigma, mode='nearest',
/// truncate)`. scipy implements the N-D filter as a sequence of 1-D correlations, one
/// per axis, with the intermediate stored at full `f64` precision. For a 2-D array that
/// is: blur along axis 0 (down columns / the row index), then blur the result along
/// axis 1 (across each row).
///
/// Kernel construction matches scipy's `_gaussian_kernel1d` exactly:
/// * radius `lw = int(truncate * sigma + 0.5)` (truncation toward zero, scipy default
///   `truncate = 4.0`),
/// * `phi[x] = exp(-0.5 / sigma^2 * x^2)` for `x in [-lw, lw]` (length `2*lw + 1`),
/// * normalized so `sum(phi) == 1`.
///
/// The kernel is symmetric (order 0), so scipy's `correlate1d` reversal is a no-op.
/// To match scipy's C accumulation order (and so reach ~1e-15 rather than ~1e-15 with a
/// different rounding), the 1-D pass accumulates the center tap first, then each
/// symmetric neighbour pair outward — the same structure scipy's symmetric-filter fast
/// path uses.
///
/// `sigma <= 1e-15` axes are skipped (matching scipy, which drops near-zero-sigma axes);
/// with a scalar sigma that means a non-positive sigma yields an unchanged copy.
///
/// # Panics
/// Panics if `field.len() != rows * cols`.
pub fn gaussian_filter_nearest(
    field: &[f64],
    rows: usize,
    cols: usize,
    sigma: f64,
    truncate: f64,
) -> Vec<f64> {
    assert_eq!(
        field.len(),
        rows * cols,
        "gaussian_filter_nearest: field.len() ({}) != rows*cols ({}*{})",
        field.len(),
        rows,
        cols
    );

    // scipy skips axes whose sigma <= 1e-15.
    if !(sigma > 1e-15) {
        return field.to_vec();
    }

    let kernel = gaussian_kernel1d(sigma, truncate);

    // Axis 0 (vertical: vary the row index). Then axis 1 (horizontal: vary the col).
    let after_axis0 = correlate1d_axis0_nearest(field, rows, cols, &kernel);
    correlate1d_axis1_nearest(&after_axis0, rows, cols, &kernel)
}

/// scipy `_gaussian_kernel1d(sigma, order=0, radius=lw)`: the normalized half-width-`lw`
/// Gaussian taps, indexed `0..=2*lw` corresponding to offsets `-lw..=lw`.
fn gaussian_kernel1d(sigma: f64, truncate: f64) -> Vec<f64> {
    let lw: i64 = (truncate * sigma + 0.5) as i64; // int(...) truncates toward zero (lw >= 0)
    let lw = lw.max(0) as usize;
    let sigma2 = sigma * sigma;
    let size = 2 * lw + 1;
    let mut phi = Vec::with_capacity(size);
    let mut sum = 0.0_f64;
    for k in 0..size {
        let x = (k as i64 - lw as i64) as f64;
        let v = (-0.5 / sigma2 * x * x).exp();
        phi.push(v);
        sum += v;
    }
    for v in phi.iter_mut() {
        *v /= sum;
    }
    phi
}

/// Clamp an index to `[0, n-1]` ('nearest'/edge-replicate boundary).
#[inline]
fn clamp_idx(i: i64, n: usize) -> usize {
    if i < 0 {
        0
    } else if i as usize >= n {
        n - 1
    } else {
        i as usize
    }
}

/// Map an out-of-bounds index using scipy's `mode='reflect'` (half-sample symmetric:
/// `(d c b a | a b c d | d c b a)` — the EDGE sample is duplicated under the fold).
///
/// Folds with period `2n`: `i' = i mod 2n` (non-negative), then if `i' >= n` reflect via
/// `2n - 1 - i'`. Matches scipy's `_extend_mode_to_code('reflect')` boundary exactly.
// Reached only via carve_ramp, whose producer seam is not wired to the runtime yet.
#[allow(dead_code)]
#[inline]
fn reflect_idx(i: i64, n: usize) -> usize {
    if n == 1 {
        return 0;
    }
    let p = 2 * n as i64;
    let mut m = i % p;
    if m < 0 {
        m += p;
    }
    if m >= n as i64 {
        (p - 1 - m) as usize
    } else {
        m as usize
    }
}

/// Gaussian blur with scipy's DEFAULT `mode='reflect'` boundary (NOT 'nearest').
///
/// Same kernel + accumulation order as [`gaussian_filter_nearest`]; only the boundary
/// extension differs ([`reflect_idx`] instead of [`clamp_idx`]). Needed where the input
/// field has large gradients up to the border (e.g. `pass_network::carve_ramp`'s gathered
/// floor profile, which descends thousands of metres along a route): there the
/// reflect-vs-nearest border difference is hundreds of metres, not the sub-metre noise the
/// 'nearest' approximation incurs on the gently-conditioned fields. Mirrors
/// `scipy.ndimage.gaussian_filter(field, sigma, truncate)` with its default mode.
// Reached only via carve_ramp, whose producer seam is not wired to the runtime yet.
#[allow(dead_code)]
pub fn gaussian_filter_reflect(
    field: &[f64],
    rows: usize,
    cols: usize,
    sigma: f64,
    truncate: f64,
) -> Vec<f64> {
    assert_eq!(
        field.len(),
        rows * cols,
        "gaussian_filter_reflect: field.len() ({}) != rows*cols ({}*{})",
        field.len(),
        rows,
        cols
    );
    if !(sigma > 1e-15) {
        return field.to_vec();
    }
    let kernel = gaussian_kernel1d(sigma, truncate);
    let after_axis0 = correlate1d_axis0_reflect(field, rows, cols, &kernel);
    correlate1d_axis1_reflect(&after_axis0, rows, cols, &kernel)
}

/// 1-D symmetric correlation along axis 0 (the row index) with scipy 'reflect' boundary.
#[allow(dead_code)]
fn correlate1d_axis0_reflect(field: &[f64], rows: usize, cols: usize, kernel: &[f64]) -> Vec<f64> {
    let lw = (kernel.len() - 1) / 2;
    let mut out = vec![0.0_f64; rows * cols];
    for x in 0..cols {
        for y in 0..rows {
            let center = field[y * cols + x];
            let mut s = center * kernel[lw];
            for j in 1..=lw {
                let plus = field[reflect_idx(y as i64 + j as i64, rows) * cols + x];
                let minus = field[reflect_idx(y as i64 - j as i64, rows) * cols + x];
                s += (plus + minus) * kernel[lw + j];
            }
            out[y * cols + x] = s;
        }
    }
    out
}

/// 1-D symmetric correlation along axis 1 (the column index) with scipy 'reflect' boundary.
#[allow(dead_code)]
fn correlate1d_axis1_reflect(field: &[f64], rows: usize, cols: usize, kernel: &[f64]) -> Vec<f64> {
    let lw = (kernel.len() - 1) / 2;
    let mut out = vec![0.0_f64; rows * cols];
    for y in 0..rows {
        let base = y * cols;
        for x in 0..cols {
            let center = field[base + x];
            let mut s = center * kernel[lw];
            for j in 1..=lw {
                let plus = field[base + reflect_idx(x as i64 + j as i64, cols)];
                let minus = field[base + reflect_idx(x as i64 - j as i64, cols)];
                s += (plus + minus) * kernel[lw + j];
            }
            out[base + x] = s;
        }
    }
    out
}

/// 1-D symmetric correlation along axis 0 (the row index) with 'nearest' boundary.
///
/// Accumulation order mirrors scipy's symmetric fast path: center tap first, then each
/// `(plus + minus) * weight` pair outward.
fn correlate1d_axis0_nearest(field: &[f64], rows: usize, cols: usize, kernel: &[f64]) -> Vec<f64> {
    let lw = (kernel.len() - 1) / 2;
    let mut out = vec![0.0_f64; rows * cols];
    for x in 0..cols {
        for y in 0..rows {
            let center = field[y * cols + x];
            let mut s = center * kernel[lw];
            for j in 1..=lw {
                let plus = field[clamp_idx(y as i64 + j as i64, rows) * cols + x];
                let minus = field[clamp_idx(y as i64 - j as i64, rows) * cols + x];
                s += (plus + minus) * kernel[lw + j];
            }
            out[y * cols + x] = s;
        }
    }
    out
}

/// 1-D symmetric correlation along axis 1 (the column index) with 'nearest' boundary.
fn correlate1d_axis1_nearest(field: &[f64], rows: usize, cols: usize, kernel: &[f64]) -> Vec<f64> {
    let lw = (kernel.len() - 1) / 2;
    let mut out = vec![0.0_f64; rows * cols];
    for y in 0..rows {
        let base = y * cols;
        for x in 0..cols {
            let center = field[base + x];
            let mut s = center * kernel[lw];
            for j in 1..=lw {
                let plus = field[base + clamp_idx(x as i64 + j as i64, cols)];
                let minus = field[base + clamp_idx(x as i64 - j as i64, cols)];
                s += (plus + minus) * kernel[lw + j];
            }
            out[base + x] = s;
        }
    }
    out
}

/// Multiple-flow-direction (MFD) accumulation over a coarse height grid.
///
/// Bit-close port of `geography_skeleton.py::_flow_accumulation_mfd(surface, power)`.
///
/// Algorithm (identical to the Python original):
/// * `acc = ones(rows*cols)`.
/// * Process cells high-to-low: `order = argsort(-hflat)`.
/// * For each cell, find its strictly-downhill 8-connected neighbours; the weight to a
///   neighbour is `(drop / dist)^power` where `drop = h_cell - h_neighbour` and `dist`
///   is 1 for orthogonal / `1.41421356237` for diagonal moves (the EXACT literal the
///   Python uses — *not* `sqrt(2)`).
/// * Distribute the cell's accumulated flow to those neighbours in proportion to weight:
///   each neighbour gains `weight * acc[cell] / (total_weight + 1e-12)`.
///
/// ## Tie ordering
/// The Python uses `np.argsort(-hflat)` (numpy default = introsort/quicksort, NOT
/// stable). Here we sort by descending height with a STABLE sort, breaking ties by
/// ascending flat index. This is deterministic and differs from numpy's order ONLY for
/// cells of *exactly equal* height. Such cells never flow to each other (the downhill
/// test is `drop > 0.0`, strict), so the processing order among tied cells changes the
/// result by at most one-ULP f64 accumulation noise (measured worst case ~8.9e-16 over
/// the fixture suite — see `export_array_ops_fixtures.py`'s tie analysis). On the noise
/// inputs there are no exact ties at all, so the match is bit-exact there.
///
/// All fields are flat row-major `f64` of length `rows * cols`.
///
/// # Panics
/// Panics if `surface.len() != rows * cols`.
pub fn flow_accumulation_mfd(surface: &[f64], rows: usize, cols: usize, power: f64) -> Vec<f64> {
    assert_eq!(
        surface.len(),
        rows * cols,
        "flow_accumulation_mfd: surface.len() ({}) != rows*cols ({}*{})",
        surface.len(),
        rows,
        cols
    );
    let n = rows * cols;
    let mut acc = vec![1.0_f64; n];
    if n == 0 {
        return acc;
    }

    // order = argsort(-hflat): cells high -> low. Stable, ties by ascending index.
    let mut order: Vec<usize> = (0..n).collect();
    order.sort_by(|&a, &b| {
        // Descending by height; NaN-free fixtures so partial_cmp is total here.
        surface[b]
            .partial_cmp(&surface[a])
            .unwrap_or(std::cmp::Ordering::Equal)
            .then(a.cmp(&b))
    });

    // EXACT offset table from the Python (dy, dx, dist) with the literal diagonal dist.
    const OFFSETS: [(i64, i64, f64); 8] = [
        (-1, -1, 1.41421356237),
        (-1, 0, 1.0),
        (-1, 1, 1.41421356237),
        (0, -1, 1.0),
        (0, 1, 1.0),
        (1, -1, 1.41421356237),
        (1, 0, 1.0),
        (1, 1, 1.41421356237),
    ];

    let p = power;
    // Reusable scratch so we distribute only after summing total (matching Python).
    let mut targets: Vec<(usize, f64)> = Vec::with_capacity(8);
    for &idx in &order {
        let y = (idx / cols) as i64;
        let x = (idx % cols) as i64;
        let hv = surface[idx];
        targets.clear();
        let mut total = 0.0_f64;
        for &(oy, ox, dist) in OFFSETS.iter() {
            let ny = y + oy;
            let nx = x + ox;
            if ny < 0 || ny >= rows as i64 || nx < 0 || nx >= cols as i64 {
                continue;
            }
            let nidx = (ny as usize) * cols + (nx as usize);
            let drop = (hv - surface[nidx]) / dist;
            if drop > 0.0 {
                let wgt = drop.powf(p);
                targets.push((nidx, wgt));
                total += wgt;
            }
        }
        if !targets.is_empty() {
            let scaled = acc[idx] / (total + 1e-12);
            for &(nidx, wgt) in targets.iter() {
                acc[nidx] += wgt * scaled;
            }
        }
    }
    acc
}
