//! Parity tests: `biome_compose.rs` (Rust) vs the Python oracle.
//!
//! Loads the committed fixture `tools/dem_pack/fixtures/biome_compose_fixture.json`
//! (generated by `tools/dem_pack/export_biome_compose_fixture.py`, which runs the REAL
//! `biome_compose.py` `_blend_field` / `_blend_height_favored` / `compose_biomes`) and
//! asserts every Rust output reproduces the Python `expected` field within a tight
//! epsilon.
//!
//! The blend/compose math is deterministic arithmetic plus a SINGLE gaussian blur per
//! recipe field in the height_favored path (`array_ops::gaussian_filter_nearest`, already
//! fixture-proven to ~1e-15), so the composed result lands at the f64 floor.
//!
//! The fixture stores the input + weight fields directly, so this test isolates the
//! blend/compose math (no noise-generator reproduction).

use crate::biome_compose::{blend_field, blend_height_favored, compose_biomes, BlendConfig};
use serde::Deserialize;

// Documented ceiling. The real max delta is printed below (~1e-13 worst case from the
// gaussian-driven favored blend; field/compose folds are ~1e-15). 1e-9 is generous
// headroom that still catches any algorithmic divergence (orders larger).
const EPS: f64 = 1e-9;

const FIXTURE: &str =
    include_str!("../../../tools/dem_pack/fixtures/biome_compose_fixture.json");

#[derive(Deserialize)]
struct Doc {
    generator_version: String,
    cfg: CfgJson,
    records: Vec<Record>,
}

#[derive(Deserialize, Clone)]
struct CfgJson {
    mode: String,
    relief_sigma_px: f64,
    favor_strength: f64,
    relief_confidence_floor: f64,
}

impl CfgJson {
    fn to_cfg(&self) -> BlendConfig {
        BlendConfig {
            mode: self.mode.clone(),
            relief_sigma_px: self.relief_sigma_px,
            favor_strength: self.favor_strength,
            relief_confidence_floor: self.relief_confidence_floor,
        }
    }
}

#[derive(Deserialize)]
struct Record {
    case: String,
    kind: String,
    rows: usize,
    cols: usize,
    // blend_* records:
    #[serde(default)]
    a: Vec<f64>,
    #[serde(default)]
    b: Vec<f64>,
    #[serde(default)]
    w_a: Vec<f64>,
    // compose records:
    #[serde(default)]
    fields: Vec<Vec<f64>>,
    #[serde(default)]
    weights: Vec<Vec<f64>>,
    cfg: CfgJson,
    expected: Vec<f64>,
}

#[test]
fn biome_compose_matches_python_oracle() {
    let doc: Doc = serde_json::from_str(FIXTURE).expect("parse biome_compose_fixture.json");
    assert_eq!(doc.generator_version, "biome_compose_fixture/v1");
    assert!(!doc.records.is_empty(), "fixture has no records");

    // Top-level cfg defaults sanity (matches Python BlendConfig() defaults).
    assert_eq!(doc.cfg.mode, "height_favored");
    assert_eq!(doc.cfg.relief_sigma_px, 6.0);
    assert_eq!(doc.cfg.favor_strength, 2.0);
    assert_eq!(doc.cfg.relief_confidence_floor, 1e-3);

    let mut max_delta = 0.0_f64;
    let mut worst = String::new();
    let mut n = 0usize;

    for r in &doc.records {
        let cfg = r.cfg.to_cfg();
        let n_px = r.rows * r.cols;
        assert_eq!(r.expected.len(), n_px, "expected len mismatch for {}", r.case);

        let got: Vec<f64> = match r.kind.as_str() {
            "blend_field" => {
                assert_eq!(r.a.len(), n_px, "a len mismatch {}", r.case);
                assert_eq!(r.b.len(), n_px, "b len mismatch {}", r.case);
                assert_eq!(r.w_a.len(), n_px, "w_a len mismatch {}", r.case);
                blend_field(&r.a, &r.b, &r.w_a)
            }
            "blend_height_favored" => {
                assert_eq!(r.a.len(), n_px, "a len mismatch {}", r.case);
                assert_eq!(r.b.len(), n_px, "b len mismatch {}", r.case);
                assert_eq!(r.w_a.len(), n_px, "w_a len mismatch {}", r.case);
                blend_height_favored(&r.a, &r.b, &r.w_a, r.rows, r.cols, &cfg)
            }
            "compose" => {
                assert!(!r.fields.is_empty(), "compose case {} has no fields", r.case);
                assert_eq!(
                    r.fields.len(),
                    r.weights.len(),
                    "fields/weights count mismatch {}",
                    r.case
                );
                for (i, f) in r.fields.iter().enumerate() {
                    assert_eq!(f.len(), n_px, "field {i} len mismatch {}", r.case);
                }
                for (i, w) in r.weights.iter().enumerate() {
                    assert_eq!(w.len(), n_px, "weight {i} len mismatch {}", r.case);
                }
                compose_biomes(&r.fields, &r.weights, r.rows, r.cols, &cfg)
            }
            other => panic!("fixture has unknown kind {other:?} for case {}", r.case),
        };

        assert_eq!(
            got.len(),
            r.expected.len(),
            "rust output len {} != fixture {} for {}",
            got.len(),
            r.expected.len(),
            r.case
        );

        let mut local_max = 0.0_f64;
        let mut at = 0usize;
        for (i, (&g, &w)) in got.iter().zip(r.expected.iter()).enumerate() {
            let d = (g - w).abs();
            if d > local_max {
                local_max = d;
                at = i;
            }
        }
        if local_max > max_delta {
            max_delta = local_max;
            worst = format!(
                "case={} kind={} cell={} got={:.17} want={:.17}",
                r.case, r.kind, at, got[at], r.expected[at]
            );
        }
        n += 1;
    }

    eprintln!("[biome_compose parity] {n} records, max |delta| = {max_delta:.3e} (worst: {worst})");

    assert!(
        max_delta < EPS,
        "biome_compose parity exceeded EPS={EPS:.1e}: max |delta|={max_delta:.3e} at {worst}"
    );
}

/// The N>2 fold uses FIELD blend (order-independent). The fixture emits the same 3
/// recipes composed in two orders (`compose_n3_triple` and `compose_n3_permuted`); both
/// match their own Python `expected`, and here we additionally assert the Rust outputs of
/// the two orders agree to f64-accumulation noise -- proving order-independence holds in
/// Rust, not just that we reproduced one ordering.
#[test]
fn biome_compose_n3_fold_is_order_independent() {
    let doc: Doc = serde_json::from_str(FIXTURE).expect("parse biome_compose_fixture.json");

    let find = |name: &str| -> &Record {
        doc.records
            .iter()
            .find(|r| r.case == name)
            .unwrap_or_else(|| panic!("fixture missing case {name}"))
    };
    let triple = find("compose_n3_triple");
    let perm = find("compose_n3_permuted");

    let got_triple = compose_biomes(
        &triple.fields,
        &triple.weights,
        triple.rows,
        triple.cols,
        &triple.cfg.to_cfg(),
    );
    let got_perm = compose_biomes(
        &perm.fields,
        &perm.weights,
        perm.rows,
        perm.cols,
        &perm.cfg.to_cfg(),
    );
    assert_eq!(got_triple.len(), got_perm.len());

    let mut max_d = 0.0_f64;
    for (&t, &p) in got_triple.iter().zip(got_perm.iter()) {
        max_d = max_d.max((t - p).abs());
    }
    eprintln!("[biome_compose] N>2 fold order-independence (rust): max |delta| = {max_d:.3e}");
    // Field-blend fold is order-independent up to the running acc_w accumulation noise.
    assert!(
        max_d < 1e-6,
        "N>2 fold not order-independent: max |delta|={max_d:.3e}"
    );
}
