//! Biome composition layer (Fork B): blend the OUTPUTS of distinct biome recipes at
//! boundaries.
//!
//! Bit-close port of `tools/dem_pack/biome_compose.py`. This layer knows nothing about
//! which recipes exist -- it takes per-recipe height fields + per-recipe weight fields
//! (a partition of unity from the grammar) and composes one height field. The blend mode
//! is tunable:
//!
//! * `height_favored` (primary): bias the blend weight toward whichever recipe has
//!   stronger LOCAL relief inside the transition band, so structured terrain stays crisp
//!   instead of being averaged into a low mound. The local-relief proxy is a gaussian
//!   blur with `mode='nearest'` (clamp-to-edge) -- the apron-safe boundary the seam-safe
//!   biome synths use (`reflect` would invent edge values and break seam-exactness of the
//!   blend at window edges). See [`crate::array_ops::gaussian_filter_nearest`].
//! * `field`: cheap weighted lerp fallback.
//!
//! Defaults mirror the Python `BlendConfig`: `mode='height_favored'`,
//! `relief_sigma_px=6.0`, `favor_strength=2.0`, `relief_confidence_floor=1e-3`.
//!
//! All fields are flat row-major (`C` order) `f64` slices of length `rows * cols`.
//! Proven by the committed fixture `tools/dem_pack/fixtures/biome_compose_fixture.json`
//! (generated by `tools/dem_pack/export_biome_compose_fixture.py`); see
//! `biome_compose_tests.rs`.

use crate::array_ops::gaussian_filter_nearest;

/// scipy's `gaussian_filter` default truncate (kernel radius = `int(truncate*sigma+0.5)`).
/// `biome_compose.py` calls `gaussian_filter(..., sigma=relief_sigma_px, mode='nearest')`
/// without overriding `truncate`, so it uses scipy's default of 4.0.
const GAUSSIAN_TRUNCATE: f64 = 4.0;

/// Tunable blend configuration. Mirrors `biome_compose.BlendConfig`.
#[derive(Clone, Debug)]
pub struct BlendConfig {
    /// `"height_favored"` (primary) or `"field"` (cheap lerp fallback).
    pub mode: String,
    /// Blur radius (px) for the local-relief proxy in the `height_favored` path.
    pub relief_sigma_px: f64,
    /// How hard to bias toward the higher-relief recipe inside the transition band.
    pub favor_strength: f64,
    /// Below this total local relief the bias fades to a plain lerp (no spurious
    /// flat-region jump).
    pub relief_confidence_floor: f64,
}

impl Default for BlendConfig {
    /// Matches `biome_compose.BlendConfig()` Python defaults exactly.
    fn default() -> Self {
        BlendConfig {
            mode: "height_favored".to_string(),
            relief_sigma_px: 6.0,
            favor_strength: 2.0,
            relief_confidence_floor: 1e-3,
        }
    }
}

/// Plain weighted lerp: `w_a` on `a`, `(1 - w_a)` on `b`. Element-wise.
///
/// Port of `biome_compose._blend_field`. All slices must have equal length.
///
/// # Panics
/// Panics if `a`, `b`, `w_a` differ in length.
pub fn blend_field(a: &[f64], b: &[f64], w_a: &[f64]) -> Vec<f64> {
    assert_eq!(a.len(), b.len(), "blend_field: a/b length mismatch");
    assert_eq!(a.len(), w_a.len(), "blend_field: a/w_a length mismatch");
    let mut out = Vec::with_capacity(a.len());
    for i in 0..a.len() {
        let w = w_a[i];
        out.push(w * a[i] + (1.0 - w) * b[i]);
    }
    out
}

/// Relief-favored blend.
///
/// Bit-close port of `biome_compose._blend_height_favored`. The local-relief proxy for a
/// field `x` is `abs(x - gaussian_filter_nearest(x, sigma=relief_sigma_px))`; the blend
/// weight is then nudged toward the higher-relief recipe inside the transition band, with
/// the nudge fading to zero where neither recipe carries local relief (flat+flat) and at
/// the pure ends (`w_a` at 0 or 1).
///
/// Exact term order (matching the Python):
/// ```text
/// relief_a = |a - gaussian_nearest(a, sigma)|
/// relief_b = |b - gaussian_nearest(b, sigma)|
/// total    = relief_a + relief_b
/// favor    = relief_a / (total + 1e-9)
/// signal   = total / (total + relief_confidence_floor)
/// band     = 1 - |2*w_a - 1|
/// w_adj    = clip(w_a + (favor - 0.5) * favor_strength * band * signal, 0, 1)
/// out      = w_adj*a + (1 - w_adj)*b
/// ```
///
/// `rows`/`cols` describe the 2-D shape used by the gaussian; the field is flat row-major.
///
/// # Panics
/// Panics if any slice length differs from `rows * cols`.
pub fn blend_height_favored(
    a: &[f64],
    b: &[f64],
    w_a: &[f64],
    rows: usize,
    cols: usize,
    cfg: &BlendConfig,
) -> Vec<f64> {
    let n = rows * cols;
    assert_eq!(a.len(), n, "blend_height_favored: a.len() != rows*cols");
    assert_eq!(b.len(), n, "blend_height_favored: b.len() != rows*cols");
    assert_eq!(w_a.len(), n, "blend_height_favored: w_a.len() != rows*cols");

    // mode='nearest' (clamp-to-edge): apron-safe boundary (reflect would invent edge
    // values and break seam-exactness of the blend at window edges).
    let blur_a = gaussian_filter_nearest(a, rows, cols, cfg.relief_sigma_px, GAUSSIAN_TRUNCATE);
    let blur_b = gaussian_filter_nearest(b, rows, cols, cfg.relief_sigma_px, GAUSSIAN_TRUNCATE);

    let mut out = Vec::with_capacity(n);
    for i in 0..n {
        let relief_a = (a[i] - blur_a[i]).abs();
        let relief_b = (b[i] - blur_b[i]).abs();
        let total_relief = relief_a + relief_b;
        let favor = relief_a / (total_relief + 1e-9); // ~1 where a has the structure
        let signal_confidence = total_relief / (total_relief + cfg.relief_confidence_floor);
        let w = w_a[i];
        let band = 1.0 - (2.0 * w - 1.0).abs(); // 1 at band center, 0 at the pure ends
        let mut w_adj = w + (favor - 0.5) * cfg.favor_strength * band * signal_confidence;
        // np.clip(..., 0.0, 1.0)
        if w_adj < 0.0 {
            w_adj = 0.0;
        } else if w_adj > 1.0 {
            w_adj = 1.0;
        }
        out.push(w_adj * a[i] + (1.0 - w_adj) * b[i]);
    }
    out
}

/// Compose N per-recipe height fields by their per-pixel weights into one height field.
///
/// Bit-close port of `biome_compose.compose_biomes`. Weights are expected to be a
/// partition of unity (sum to ~1 per pixel) from the grammar.
///
/// Fold semantics (exactly the Python):
/// * `fields.len() == 1` returns `fields[0]` unchanged.
/// * `use_favored = (cfg.mode != "field") && (fields.len() == 2)`. `height_favored` is
///   applied EXACTLY for the N==2 boundary case; for 3+ recipes meeting (rare triple
///   points) we fold with FIELD blend so the result is order-independent (the relief bias
///   would otherwise compound on the running accumulator and make the result depend on
///   `fields` order).
/// * Running accumulator: start with `acc = fields[0]`, `acc_w = weights[0]`. For each
///   subsequent `(f, w)`: `denom = acc_w + w + 1e-12`, `w_acc = acc_w / denom` (the weight
///   on the accumulator vs the new recipe), blend `acc` with `f` using `w_acc`, then
///   `acc_w += w`.
///
/// `rows`/`cols` are the 2-D shape (needed only by the favored path's gaussian); each
/// field/weight is flat row-major of length `rows * cols`.
///
/// # Panics
/// Panics if `fields.len() != weights.len()`, if `fields` is empty, or if any field/weight
/// length differs from `rows * cols`.
pub fn compose_biomes(
    fields: &[Vec<f64>],
    weights: &[Vec<f64>],
    rows: usize,
    cols: usize,
    cfg: &BlendConfig,
) -> Vec<f64> {
    // STRICT mode validation (mirrors the Python fix): an unknown/typo'd mode must NOT silently
    // fall through to height_favored. Only the two known modes are accepted.
    assert!(
        cfg.mode == "height_favored" || cfg.mode == "field",
        "BlendConfig.mode must be \"height_favored\" or \"field\", got {:?}",
        cfg.mode
    );
    assert_eq!(
        fields.len(),
        weights.len(),
        "compose_biomes: fields/weights length mismatch: {} vs {}",
        fields.len(),
        weights.len()
    );
    assert!(
        !fields.is_empty(),
        "compose_biomes requires at least one recipe field"
    );
    let n = rows * cols;
    for (i, f) in fields.iter().enumerate() {
        assert_eq!(f.len(), n, "compose_biomes: field {i} len != rows*cols");
    }
    for (i, w) in weights.iter().enumerate() {
        assert_eq!(w.len(), n, "compose_biomes: weight {i} len != rows*cols");
    }

    if fields.len() == 1 {
        return fields[0].clone();
    }

    let mut acc = fields[0].clone();
    let mut acc_w = weights[0].clone();
    let use_favored = (cfg.mode == "height_favored") && (fields.len() == 2);

    for (f, w) in fields.iter().skip(1).zip(weights.iter().skip(1)) {
        // w_acc = acc_w / (acc_w + w + 1e-12): weight on the accumulator vs the new recipe.
        let mut w_acc = Vec::with_capacity(n);
        for i in 0..n {
            let denom = acc_w[i] + w[i] + 1e-12;
            w_acc.push(acc_w[i] / denom);
        }

        acc = if use_favored {
            blend_height_favored(&acc, f, &w_acc, rows, cols, cfg)
        } else {
            blend_field(&acc, f, &w_acc)
        };

        for i in 0..n {
            acc_w[i] += w[i];
        }
    }

    acc
}
