//! Parity tests: `recipe_noise.rs` (Rust) vs `worldgen_proto.py` (the offline oracle).
//!
//! Loads the committed fixture `tools/dem_pack/fixtures/recipe_noise_fixtures.json`
//! (generated by `tools/dem_pack/export_recipe_noise_fixtures.py`) and asserts every
//! Rust primitive reproduces the Python `expected_output` within a tight epsilon.
//! These are deterministic f64 computations on identical inputs, so the achievable
//! delta is ~machine-epsilon; EPS below is the documented ceiling, not the actual gap.

use crate::recipe_noise as rn;
use serde::Deserialize;

// Tight epsilon: identical f64 ops on identical inputs => bit-exact in practice.
// We allow a hair of slack (1e-12) only to be robust to JSON float round-trip of
// the expected values; the test prints the real max delta so regressions surface.
const EPS: f64 = 1e-12;

const FIXTURE: &str =
    include_str!("../../../tools/dem_pack/fixtures/recipe_noise_fixtures.json");

#[derive(Deserialize)]
struct Doc {
    generator_version: String,
    records: Vec<Record>,
}

#[derive(Deserialize)]
struct Record {
    primitive: String,
    inputs: serde_json::Value,
    expected_output: serde_json::Value,
}

fn f(v: &serde_json::Value, key: &str) -> f64 {
    v.get(key)
        .and_then(|x| x.as_f64())
        .unwrap_or_else(|| panic!("missing/invalid f64 field {key} in {v}"))
}

fn i(v: &serde_json::Value, key: &str) -> i64 {
    v.get(key)
        .and_then(|x| x.as_i64())
        .unwrap_or_else(|| panic!("missing/invalid i64 field {key} in {v}"))
}

#[test]
fn recipe_noise_matches_python_oracle() {
    let doc: Doc = serde_json::from_str(FIXTURE).expect("parse recipe_noise_fixtures.json");
    assert_eq!(doc.generator_version, "recipe_noise_fixtures/v1");
    assert!(!doc.records.is_empty(), "fixture has no records");

    let mut max_delta = 0.0_f64;
    let mut worst = String::new();
    let mut checked = 0usize;

    for r in &doc.records {
        let inp = &r.inputs;
        let exp = &r.expected_output;
        match r.primitive.as_str() {
            "value_noise" => {
                let got = rn::value_noise(f(inp, "wx"), f(inp, "wz"), i(inp, "seed"));
                let want = exp.as_f64().expect("scalar expected_output");
                track(&mut max_delta, &mut worst, &r.primitive, inp, got, want);
            }
            "fbm" => {
                let got = rn::fbm(
                    f(inp, "wx"), f(inp, "wz"), f(inp, "base_freq"),
                    i(inp, "octaves") as u32, i(inp, "seed"),
                    f(inp, "gain"), f(inp, "lacunarity"),
                );
                let want = exp.as_f64().unwrap();
                track(&mut max_delta, &mut worst, &r.primitive, inp, got, want);
            }
            "ridged_fbm" => {
                let got = rn::ridged_fbm(
                    f(inp, "wx"), f(inp, "wz"), f(inp, "base_freq"),
                    i(inp, "octaves") as u32, i(inp, "seed"),
                    f(inp, "gain"), f(inp, "lacunarity"),
                );
                let want = exp.as_f64().unwrap();
                track(&mut max_delta, &mut worst, &r.primitive, inp, got, want);
            }
            "ridged_multifractal" => {
                let got = rn::ridged_multifractal(
                    f(inp, "wx"), f(inp, "wz"), f(inp, "base_freq"),
                    i(inp, "octaves") as u32, i(inp, "seed"),
                    f(inp, "gain"), f(inp, "lacunarity"),
                    f(inp, "offset"), f(inp, "weight_gain"),
                );
                let want = exp.as_f64().unwrap();
                track(&mut max_delta, &mut worst, &r.primitive, inp, got, want);
            }
            "domain_warp" => {
                let (gx, gz) = rn::domain_warp(
                    f(inp, "wx"), f(inp, "wz"),
                    f(inp, "warp_amount"), f(inp, "warp_freq"), i(inp, "seed"),
                );
                track(&mut max_delta, &mut worst, "domain_warp.x", inp, gx, f(exp, "out_x"));
                track(&mut max_delta, &mut worst, "domain_warp.z", inp, gz, f(exp, "out_z"));
                checked += 1; // counts as one record (two components)
            }
            "recursive_domain_warp" => {
                let (gx, gz) = rn::recursive_domain_warp(
                    f(inp, "wx"), f(inp, "wz"),
                    f(inp, "warp_amount"), f(inp, "warp_freq"), i(inp, "seed"),
                    i(inp, "steps") as u32, f(inp, "decay"), f(inp, "freq_mul"),
                );
                track(&mut max_delta, &mut worst, "recursive_domain_warp.x", inp, gx, f(exp, "out_x"));
                track(&mut max_delta, &mut worst, "recursive_domain_warp.z", inp, gz, f(exp, "out_z"));
                checked += 1;
            }
            "cellular_edges" => {
                let got = rn::cellular_edges(
                    f(inp, "wx"), f(inp, "wz"), f(inp, "freq"),
                    i(inp, "seed"), f(inp, "sharpness"),
                );
                let want = exp.as_f64().unwrap();
                track(&mut max_delta, &mut worst, &r.primitive, inp, got, want);
            }
            "range_spine_field" => {
                let got = rn::range_spine_field(
                    f(inp, "wx"), f(inp, "wz"), f(inp, "cell_size"),
                    f(inp, "width"), i(inp, "seed"), i(inp, "neighborhood") as i32,
                );
                let want = exp.as_f64().unwrap();
                track(&mut max_delta, &mut worst, &r.primitive, inp, got, want);
            }
            "fault_block_field" => {
                let got = rn::fault_block_field(
                    f(inp, "wx"), f(inp, "wz"), f(inp, "cell_size"),
                    f(inp, "width"), i(inp, "seed"), i(inp, "neighborhood") as i32,
                );
                let want = exp.as_f64().unwrap();
                track(&mut max_delta, &mut worst, &r.primitive, inp, got, want);
            }
            other => panic!("fixture has unknown primitive {other:?}"),
        }
        checked += 1;
    }

    eprintln!(
        "[recipe_noise parity] checked {checked} records over 9 primitives; \
         max |delta| = {max_delta:.3e} (worst: {worst})"
    );
    assert!(
        max_delta < EPS,
        "recipe_noise parity exceeded EPS={EPS:.1e}: max |delta|={max_delta:.3e} at {worst}"
    );
}

fn track(max: &mut f64, worst: &mut String, name: &str, inp: &serde_json::Value, got: f64, want: f64) {
    let d = (got - want).abs();
    if d > *max {
        *max = d;
        *worst = format!("{name} inputs={inp} got={got:.17} want={want:.17}");
    }
}
