//! Recipe-level parity test: `recipes_volcanic.rs` (Rust) vs the Python recipe oracle.
//!
//! Loads the committed fixture `tools/dem_pack/fixtures/recipe_volcanic_fixture.json`
//! (generated by `tools/dem_pack/export_recipe_volcanic_fixture.py`, which runs the REAL
//! `volcanic_synthesis.generate(apron_px=160)` seam-safe path), rebuilds the same
//! apron-padded world grid, runs `recipes_volcanic::volcanic_seamsafe(...)`, and asserts
//! the core-cropped height reproduces the Python `height` within a tight epsilon.
//!
//! Mirrors `recipes_tests.rs` (the mountain template). The volcanic pipeline adds an
//! explicit vent/cone/crater/shield/lava-flow construction plus a numpy PCG64 random
//! stream for vent placement (reproduced bit-close in `npy_random`); everything else
//! (recursive warp, fbm/ridged_multifractal, whole-array gaussians, MFD gully channels,
//! affine remaps) reuses the same already-fixture-proven primitives, so the composed
//! recipe is expected near the f64 floor.

use crate::recipes::helpers;
use crate::recipes_volcanic::{volcanic, volcanic_seamsafe};
use serde::Deserialize;

// Documented ceiling. The real max delta is printed below. 1e-9 is generous headroom
// that still catches any algorithmic divergence (which would be orders larger). The
// vent-placement normal draws use an analytically-reconstructed ziggurat that matches
// numpy to ~5e-12; through the smooth cone/blur pipeline that lands far below this EPS.
const EPS: f64 = 1e-9;

const FIXTURE: &str =
    include_str!("../../../tools/dem_pack/fixtures/recipe_volcanic_fixture.json");

#[derive(Deserialize)]
struct Doc {
    generator_version: String,
    records: Vec<Record>,
}

#[derive(Deserialize)]
struct Grid {
    spacing: f64,
    ox: f64,
    oz: f64,
}

#[derive(Deserialize)]
struct Record {
    recipe: String,
    seed: i64,
    feature_span_m: f64,
    apron_px: usize,
    style_key: String,
    core_rows: usize,
    core_cols: usize,
    padded_rows: usize,
    padded_cols: usize,
    grid: Grid,
    height: Vec<f64>,
}

#[test]
fn volcanic_seamsafe_matches_python_oracle() {
    let doc: Doc = serde_json::from_str(FIXTURE).expect("parse recipe_volcanic_fixture.json");
    assert_eq!(doc.generator_version, "recipe_fixtures/v1");
    assert!(!doc.records.is_empty(), "fixture has no records");

    let mut max_delta = 0.0_f64;
    let mut worst = String::new();
    let mut n = 0usize;

    for r in &doc.records {
        assert_eq!(r.recipe, "volcanic_seamsafe", "unexpected recipe {}", r.recipe);
        assert_eq!(
            r.style_key, "stratovolcano_cluster",
            "fixture style {} != STYLES[0]",
            r.style_key
        );
        assert_eq!(
            r.apron_px,
            volcanic::APRON_PX,
            "fixture apron {} != volcanic::APRON_PX",
            r.apron_px
        );
        assert_eq!(
            r.height.len(),
            r.core_rows * r.core_cols,
            "fixture height len mismatch"
        );

        // Rebuild the identical apron-padded grid the Python exporter used.
        let (wx, wz) = helpers::apron_meshgrid(
            r.padded_rows,
            r.padded_cols,
            r.apron_px,
            r.grid.spacing,
            r.grid.ox,
            r.grid.oz,
        );

        let got = volcanic_seamsafe(
            &wx,
            &wz,
            r.padded_rows,
            r.padded_cols,
            r.seed,
            r.feature_span_m,
            r.apron_px,
        );

        assert_eq!(
            got.len(),
            r.height.len(),
            "rust core len {} != fixture {}",
            got.len(),
            r.height.len()
        );

        let mut local_max = 0.0_f64;
        let mut at = 0usize;
        for (i, (&g, &w)) in got.iter().zip(r.height.iter()).enumerate() {
            let d = (g - w).abs();
            if d > local_max {
                local_max = d;
                at = i;
            }
        }
        if local_max > max_delta {
            max_delta = local_max;
            worst = format!(
                "seed={} cell={} got={:.17} want={:.17}",
                r.seed, at, got[at], r.height[at]
            );
        }
        n += 1;
    }

    eprintln!(
        "[recipe volcanic parity] {n} records, max |delta| = {max_delta:.3e} (worst: {worst})"
    );

    assert!(
        max_delta < EPS,
        "volcanic_seamsafe parity exceeded EPS={EPS:.1e}: max |delta|={max_delta:.3e} at {worst}"
    );
}

/// The CPU vent-buffer packing (`volcanic::packed_vents`) is what the GPU consumes -- it MUST
/// reproduce the recipe's two RNG streams exactly (the whole "RNG stays in Rust" insight rides on
/// this). The proven `vent_points`/flow-dir RNG inside `vent_fields` is private, so we pin
/// `packed_vents` against numpy ground truth (the SAME values `rng_unit_tests` already validate the
/// raw streams against): for STYLES[0], seed=0, span=60000:
///   * vent0 is the FIXED-origin normal-jittered centre with amp 1.08; its (vx,vz) are
///     (0 + normal(0, span*0.08), 0 + normal(0, span*0.08)) = (3350.088848951808, -4163.82158704271)
///     (numpy default_rng(500).normal(0,4800) x2 -- see pcg64_random_matches_numpy_seed500).
///   * vent0's 4 flow dirs are the first 4 uniform(-PI,PI) of default_rng(900):
///     -3.10801602613677, -2.8620128338816295, 2.5596769870805165, ... (see
///     pcg64_uniform_matches_numpy_seed900).
/// vent_count must be 4 (stratovolcano_cluster) and the buffer length MAX_VENTS*VENT_STRIDE.
#[test]
fn packed_vents_matches_numpy_streams_seed0() {
    use std::f64::consts::PI;
    let (packed, count) =
        volcanic::packed_vents(&volcanic::STRATOVOLCANO_CLUSTER, 0, 60000.0);
    assert_eq!(count, 4, "stratovolcano_cluster vent_count");
    assert_eq!(packed.len(), volcanic::MAX_VENTS * volcanic::VENT_STRIDE);

    // vent0 (slot 0): vx, vz, amp, dir0..dir3.
    let vx = packed[0] as f64;
    let vz = packed[1] as f64;
    let amp = packed[2] as f64;
    let d0 = packed[3] as f64;
    let d1 = packed[4] as f64;
    let d2 = packed[5] as f64;
    // f32-narrowed, so compare at f32 precision (~1e-3 on metre-scale coords).
    assert!((vx - 3350.088848951808).abs() < 1.0, "vent0 vx={vx}");
    assert!((vz - (-4163.82158704271)).abs() < 1.0, "vent0 vz={vz}");
    assert!((amp - 1.08).abs() < 1e-5, "vent0 amp={amp}");
    assert!((d0 - (-3.10801602613677)).abs() < 1e-5, "vent0 dir0={d0}");
    assert!((d1 - (-2.8620128338816295)).abs() < 1e-5, "vent0 dir1={d1}");
    assert!((d2 - 2.5596769870805165).abs() < 1e-5, "vent0 dir2={d2}");
    // all dirs are uniform draws in [-PI, PI].
    for vi in 0..count {
        for k in 3..7 {
            let dir = packed[vi * volcanic::VENT_STRIDE + k] as f64;
            assert!(dir >= -PI - 1e-4 && dir <= PI + 1e-4, "dir out of range: {dir}");
        }
    }
    // padding past vent_count is zero.
    for vi in count..volcanic::MAX_VENTS {
        for k in 0..volcanic::VENT_STRIDE {
            assert_eq!(packed[vi * volcanic::VENT_STRIDE + k], 0.0, "pad not zero");
        }
    }
}

/// Seed 7 (the fixture's second record): vent_count must also be 4 and fit MAX_VENTS, and the
/// packing must be deterministic (the GPU buffer is rebuilt per page from these seeds).
#[test]
fn packed_vents_seed7_is_four_vents() {
    let (packed, count) =
        volcanic::packed_vents(&volcanic::STRATOVOLCANO_CLUSTER, 7, 60000.0);
    assert_eq!(count, 4);
    assert_eq!(packed.len(), volcanic::MAX_VENTS * volcanic::VENT_STRIDE);
    // deterministic: same seed -> same bytes.
    let (packed2, count2) =
        volcanic::packed_vents(&volcanic::STRATOVOLCANO_CLUSTER, 7, 60000.0);
    assert_eq!(count, count2);
    assert_eq!(packed, packed2);
}
