//! Recipe-level parity test: `recipes_volcanic.rs` (Rust) vs the Python recipe oracle.
//!
//! Loads the committed fixture `tools/dem_pack/fixtures/recipe_volcanic_fixture.json`
//! (generated by `tools/dem_pack/export_recipe_volcanic_fixture.py`, which runs the REAL
//! `volcanic_synthesis.generate(apron_px=160)` seam-safe path), rebuilds the same
//! apron-padded world grid, runs `recipes_volcanic::volcanic_seamsafe(...)`, and asserts
//! the core-cropped height reproduces the Python `height` within a tight epsilon.
//!
//! Mirrors `recipes_tests.rs` (the mountain template). The volcanic pipeline adds an
//! explicit vent/cone/crater/shield/lava-flow construction plus a numpy PCG64 random
//! stream for vent placement (reproduced bit-close in `npy_random`); everything else
//! (recursive warp, fbm/ridged_multifractal, whole-array gaussians, MFD gully channels,
//! affine remaps) reuses the same already-fixture-proven primitives, so the composed
//! recipe is expected near the f64 floor.

use crate::recipes::helpers;
use crate::recipes_volcanic::{volcanic, volcanic_seamsafe};
use serde::Deserialize;

// Documented ceiling. The real max delta is printed below. 1e-9 is generous headroom
// that still catches any algorithmic divergence (which would be orders larger). The
// vent-placement normal draws use an analytically-reconstructed ziggurat that matches
// numpy to ~5e-12; through the smooth cone/blur pipeline that lands far below this EPS.
const EPS: f64 = 1e-9;

const FIXTURE: &str =
    include_str!("../../../tools/dem_pack/fixtures/recipe_volcanic_fixture.json");

#[derive(Deserialize)]
struct Doc {
    generator_version: String,
    records: Vec<Record>,
}

#[derive(Deserialize)]
struct Grid {
    spacing: f64,
    ox: f64,
    oz: f64,
}

#[derive(Deserialize)]
struct Record {
    recipe: String,
    seed: i64,
    feature_span_m: f64,
    apron_px: usize,
    style_key: String,
    core_rows: usize,
    core_cols: usize,
    padded_rows: usize,
    padded_cols: usize,
    grid: Grid,
    height: Vec<f64>,
}

#[test]
fn volcanic_seamsafe_matches_python_oracle() {
    let doc: Doc = serde_json::from_str(FIXTURE).expect("parse recipe_volcanic_fixture.json");
    assert_eq!(doc.generator_version, "recipe_fixtures/v1");
    assert!(!doc.records.is_empty(), "fixture has no records");

    let mut max_delta = 0.0_f64;
    let mut worst = String::new();
    let mut n = 0usize;

    for r in &doc.records {
        assert_eq!(r.recipe, "volcanic_seamsafe", "unexpected recipe {}", r.recipe);
        assert_eq!(
            r.style_key, "stratovolcano_cluster",
            "fixture style {} != STYLES[0]",
            r.style_key
        );
        assert_eq!(
            r.apron_px,
            volcanic::APRON_PX,
            "fixture apron {} != volcanic::APRON_PX",
            r.apron_px
        );
        assert_eq!(
            r.height.len(),
            r.core_rows * r.core_cols,
            "fixture height len mismatch"
        );

        // Rebuild the identical apron-padded grid the Python exporter used.
        let (wx, wz) = helpers::apron_meshgrid(
            r.padded_rows,
            r.padded_cols,
            r.apron_px,
            r.grid.spacing,
            r.grid.ox,
            r.grid.oz,
        );

        let got = volcanic_seamsafe(
            &wx,
            &wz,
            r.padded_rows,
            r.padded_cols,
            r.seed,
            r.feature_span_m,
            r.apron_px,
        );

        assert_eq!(
            got.len(),
            r.height.len(),
            "rust core len {} != fixture {}",
            got.len(),
            r.height.len()
        );

        let mut local_max = 0.0_f64;
        let mut at = 0usize;
        for (i, (&g, &w)) in got.iter().zip(r.height.iter()).enumerate() {
            let d = (g - w).abs();
            if d > local_max {
                local_max = d;
                at = i;
            }
        }
        if local_max > max_delta {
            max_delta = local_max;
            worst = format!(
                "seed={} cell={} got={:.17} want={:.17}",
                r.seed, at, got[at], r.height[at]
            );
        }
        n += 1;
    }

    eprintln!(
        "[recipe volcanic parity] {n} records, max |delta| = {max_delta:.3e} (worst: {worst})"
    );

    assert!(
        max_delta < EPS,
        "volcanic_seamsafe parity exceeded EPS={EPS:.1e}: max |delta|={max_delta:.3e} at {worst}"
    );
}
